name: Orion ERP CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  api-ci:
    name: API Build & Basic Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: orion-api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Basic syntax check
        run: |
          python -m compileall app

      - name: Run tests
        run: |
          python -m  pytest

  api-docker-build:
    name: API Docker Image Build
    runs-on: ubuntu-latest
    needs: api-ci

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: |
          docker build -t orion-api:ci-test ./orion-api
